### ISSUE TITLE
Error: Caching an already local asset is not yet supported.

### ISSUE THREAD

**Issue by tannerdolby** [colabottles/dgc#2]
> [1] Error: Caching an already local asset is not yet supported.

@colabottles / @toddlibby The build process throws the above error.

I noticed `food.js` utilizes `eleventy-cache-assets` for getting the **remote** data from `menu.json` and returns an object, which I presume would be used somewhere in a template to use the cached data on page. I couldn't find anywhere in the project where this utility was actually being used. 

Could you explain the need for this?

To my understanding:
- `../_data/menu.json'` is already a local asset so why would it need to be cached if an API isn't involved to grab **remote** data from? 
- I guess having the data already cached makes sense in theory but since we are building a static site, the menu assets in `menu.json` should already be available to us without having to run an `async` function to cache things.

**Comment by colabottles** [comment]
@tannerdolby I was linking to a .json file that was not there so it is not being used. the example taken from Andy Bell's site was using an external .json file. Glad you brought this up or I would have forgotten it. The .json file I had intended to use in the project as a local asset so this was an oversight on my part.

**Comment by tannerdolby** [comment]
Ah, I see. I can now for certain say that the utility should be removed as its not being used. Closing this issue.

P.S. - I haven't removed the `food.js` file from the project, I'll leave that to you if you choose to do so. It will get rid of the single error present at build time.
